COMPUTED VALUES:
githubConfigSecret: github-app-secret
githubConfigUrl: https://github.com/johno10661/sop
maxRunners: 4
minRunners: 1
namespaceOverride: ""
runnerScaleSetName: runners-sop-amd64
template:
  spec:
    containers:
    - command:
      - /home/runner/run.sh
      image: ghcr.io/ediai-dev/arc-runner:latest
      name: runner
      volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
    imagePullSecrets:
    - name: ghcr-pull-secret
    nodeSelector:
      kubernetes.io/arch: amd64
    volumes:
    - hostPath:
        path: /var/run/docker.sock
      name: docker-sock
